version: '3.7'

services:
  cockroach1:
    image: cockroachdb/cockroach:v24.2.9
    command: >
      start --insecure
      --listen-addr=0.0.0.0
      --http-addr=0.0.0.0:8080
      --advertise-addr=cockroach1
      --join=host.containers.internal:26257
    ports:
      - "26257:26257"
      - "8080:8080"

  cockroach2:
    image: cockroachdb/cockroach:v24.2.9
    command: >
      start --insecure
      --listen-addr=0.0.0.0
      --http-addr=0.0.0.0:8080
      --advertise-addr=cockroach2
      --join=host.containers.internal:26257

  cockroach3:
    image: cockroachdb/cockroach:v24.2.9
    command: >
      start --insecure
      --listen-addr=0.0.0.0
      --http-addr=0.0.0.0:8080
      --advertise-addr=cockroach3
      --join=host.containers.internal:26257
